server {
    listen 80;

    # Serve frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Forward /api requests to backend
    location /api {
        proxy_pass http://${BACKEND_URL}:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
